name: Kubernetes CD Pipeline
    types:
      - completed

jobs:
  deploy:

    # Only deploy if CI passed
    if: ${{ github.event.workflow_run.conclusion == 'success' }}

    runs-on: self-hosted

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      # ---------------- BACKEND IMAGE ----------------

      - name: Build Backend Docker Image
        run: |
          docker build -t wahed1321/calculator-app:latest .

      - name: Push Backend Docker Image
        run: |
          docker push wahed1321/calculator-app:latest

      # ---------------- FRONTEND IMAGE ----------------

      - name: Build Frontend Docker Image
        run: |
          docker build -t wahed1321/calculator-frontend:latest ./frontend

      - name: Push Frontend Docker Image
        run: |
          docker push wahed1321/calculator-frontend:latest

      # ---------------- KUBERNETES DEPLOYMENT ----------------

      - name: Apply Kubernetes Files
        run: |
          kubectl apply -f k8s/

      - name: Restart Backend Deployment
        run: |
          kubectl rollout restart deployment devops-app

      - name: Restart Frontend Deployment
        run: |
          kubectl rollout restart deployment frontend-app

      - name: Verify Deployments
        run: |
          kubectl get pods
          kubectl get svc
          kubectl get ingress
